clear; clc; close all
set(0,'DefaultFigureWindowStyle','docked')
set(0,'defaultTextInterpreter','none') % 'latex'

vmax=12;
warning('off')

cd 'C:\Users\mirta\Dropbox\SFI Reconquista\00 strategies\analyses\trees50'
a=dir;

tree_data=readtable('tree_data2.xls');

%% import results of ardl and prep for meta in stata - tox joint 
pathreg="C:\Users\mirta\Dropbox\SFI Reconquista\00 strategies\analyses\trees50\tox_joint_rob3\";

varnames={'L.zee_tox';'L2.zee_tox';'zee_strategy_opin';'zee_strategy_sarc';'zee_strategy_construct';...    
    'zee_goal2_out_negative';'zee_goal2_in_both_positive';'zee_anger';'zee_fear';...
    'zee_disgust';'zee_sadness';'zee_enthop';'zee_prijoy'; ...
    'L.zee_strategy_opin';'L.zee_strategy_sarc';'L.zee_strategy_construct';...    
    'L.zee_goal2_out_negative';'L.zee_goal2_in_both_positive';'L.zee_anger';'L.zee_fear';...
    'L.zee_disgust';'L.zee_sadness';'L.zee_enthop';'L.zee_prijoy'; ...
    'L2.zee_strategy_opin';'L2.zee_strategy_sarc';'L2.zee_strategy_construct';...    
    'L2.zee_goal2_out_negative';'L2.zee_goal2_in_both_positive';'L2.zee_anger';'L2.zee_fear';...
    'L2.zee_disgust';'L2.zee_sadness';'L2.zee_enthop';'L2.zee_prijoy'; ...
    'tweet_nr3';'_cons';'N'};
varnames2= ...
    {'L1_zee_tox';'L2_zee_tox';'zee_strategy_opin';'zee_strategy_sarc';'zee_strategy_construct';...    
    'zee_goal2_out_negative';'zee_goal2_in_both_positive';'zee_anger';'zee_fear';...
    'zee_disgust';'zee_sadness';'zee_enthop';'zee_prijoy'; ...
    'L1_zee_strategy_opin';'L1_zee_strategy_sarc';'L1_zee_strategy_construct';...    
    'L1_zee_goal2_out_negative';'L1_zee_goal2_in_both_positive';'L1_zee_anger';'L1_zee_fear';...
    'L1_zee_disgust';'L1_zee_sadness';'L1_zee_enthop';'L1_zee_prijoy'; ...
    'L2_zee_strategy_opin';'L2_zee_strategy_sarc';'L2_zee_strategy_construct';...    
    'L2_zee_goal2_out_negative';'L2_zee_goal2_in_both_positive';'L2_zee_anger';'L2_zee_fear';...
    'L2_zee_disgust';'L2_zee_sadness';'L2_zee_enthop';'L2_zee_prijoy'; ...
    'tweet_nr3';'_cons';'N';...
    'se_L1_zee_tox';'se_L2_zee_tox';'se_zee_strategy_opin';'se_zee_strategy_sarc';'se_zee_strategy_construct';...    
    'se_zee_goal2_out_negative';'se_zee_goal2_in_both_positive';'se_zee_anger';'se_zee_fear';...
    'se_zee_disgust';'se_zee_sadness';'se_zee_enthop'; 'se_zee_prijoy';...
    'se_L1_zee_strategy_opin';'se_L1_zee_strategy_sarc';'se_L1_zee_strategy_construct';...    
    'se_L1_zee_goal2_out_negative';'se_L1_zee_goal2_in_both_positive';'se_L1_zee_anger';'se_L1_zee_fear';...
    'se_L1_zee_disgust';'se_L1_zee_sadness';'se_L1_zee_enthop';'se_L1_zee_prijoy'; ...
    'se_L2_zee_strategy_opin';'se_L2_zee_strategy_sarc';'se_L2_zee_strategy_construct';...    
    'se_L2_zee_goal2_out_negative';'se_L2_zee_goal2_in_both_positive';'se_L2_zee_anger';'se_L2_zee_fear';...
    'se_L2_zee_disgust';'se_L2_zee_sadness';'se_L2_zee_enthop';'se_L2_zee_prijoy'; ...
    'se_tweet_nr3';'se__cons';'drop';'regnum'};
    
for type=1:3

    data = cell2table(cell(0,length(varnames2)),'VariableNames', varnames2);
    jjs=tree_data.regnum(tree_data.root_type==type);

for j=1:length(jjs)
    try
    j
    temp=readtable(pathreg + "regs_tox_d_basic_50_" + num2str(j) +".xlsx.csv",'Format','%s %s','ReadRowNames',false);
    temp(end,:)=[];
    for i=2:2:height(temp)-2
        if length(temp{i,1}{1})>3
            
            % Remove = and quotes, convert to number
            coef = str2double(regexprep(temp{i,2}{1},'[="()]',''));
            se = str2double(regexprep(temp{i+1,2}{1},'[="()]',''));
            name = regexprep(temp{i,1}{1},'[="()]','');
            name = strrep(name, 'L.', 'L1_');
            name = strrep(name, 'L2.', 'L2_');
            se_name=['se_' name];
            
            data{j,strcmp(name,varnames2)}=coef;
            data{j,strcmp(se_name,varnames2)}=se;
        end
    end
    data{j,strcmp("N",varnames2)}=str2double(regexprep(temp{height(temp),2}{1},'[="()]',''));
    data{j,end}=j;    
    end
end
data.Properties.VariableNames{'_cons'} = 'cons';
data.Properties.VariableNames{'se__cons'} = 'se_cons';
temp=table2array(data); temp(temp==0)=nan;data{:,:}=temp; 
writetable(data,pathreg + "for_meta_type" + num2str(type) + ".xlsx");

end

%% import results of ardl and prep for meta in stata - extreme speech joint 
pathreg="C:\Users\mirta\Dropbox\SFI Reconquista\00 strategies\analyses\trees50\extsp_joint_rob3\";

varnames={'L.zee_extreme_score';'L2.zee_extreme_score';'zee_strategy_opin';'zee_strategy_sarc';'zee_strategy_construct';...    
    'zee_goal2_out_negative';'zee_goal2_in_both_positive';'zee_anger';'zee_fear';...
    'zee_disgust';'zee_sadness';'zee_enthop';'zee_prijoy'; ...
    'L.zee_strategy_opin';'L.zee_strategy_sarc';'L.zee_strategy_construct';...    
    'L.zee_goal2_out_negative';'L.zee_goal2_in_both_positive';'L.zee_anger';'L.zee_fear';...
    'L.zee_disgust';'L.zee_sadness';'L.zee_enthop';'L.zee_prijoy'; ...
    'L2.zee_strategy_opin';'L2.zee_strategy_sarc';'L2.zee_strategy_construct';...    
    'L2.zee_goal2_out_negative';'L2.zee_goal2_in_both_positive';'L2.zee_anger';'L2.zee_fear';...
    'L2.zee_disgust';'L2.zee_sadness';'L2.zee_enthop';'L2.zee_prijoy'; ...
    'tweet_nr3';'_cons';'N'};
varnames2= ...
    {'L1_zee_extreme_score';'L2_zee_extreme_score';'zee_strategy_opin';'zee_strategy_sarc';'zee_strategy_construct';...    
    'zee_goal2_out_negative';'zee_goal2_in_both_positive';'zee_anger';'zee_fear';...
    'zee_disgust';'zee_sadness';'zee_enthop';'zee_prijoy'; ...
    'L1_zee_strategy_opin';'L1_zee_strategy_sarc';'L1_zee_strategy_construct';...    
    'L1_zee_goal2_out_negative';'L1_zee_goal2_in_both_positive';'L1_zee_anger';'L1_zee_fear';...
    'L1_zee_disgust';'L1_zee_sadness';'L1_zee_enthop';'L1_zee_prijoy'; ...
    'L2_zee_strategy_opin';'L2_zee_strategy_sarc';'L2_zee_strategy_construct';...    
    'L2_zee_goal2_out_negative';'L2_zee_goal2_in_both_positive';'L2_zee_anger';'L2_zee_fear';...
    'L2_zee_disgust';'L2_zee_sadness';'L2_zee_enthop';'L2_zee_prijoy'; ...
    'tweet_nr3';'_cons';'N';...
    'se_L1_zee_extreme_score';'se_L2_zee_extreme_score';'se_zee_strategy_opin';'se_zee_strategy_sarc';'se_zee_strategy_construct';...    
    'se_zee_goal2_out_negative';'se_zee_goal2_in_both_positive';'se_zee_anger';'se_zee_fear';...
    'se_zee_disgust';'se_zee_sadness';'se_zee_enthop'; 'se_zee_prijoy';...
    'se_L1_zee_strategy_opin';'se_L1_zee_strategy_sarc';'se_L1_zee_strategy_construct';...    
    'se_L1_zee_goal2_out_negative';'se_L1_zee_goal2_in_both_positive';'se_L1_zee_anger';'se_L1_zee_fear';...
    'se_L1_zee_disgust';'se_L1_zee_sadness';'se_L1_zee_enthop';'se_L1_zee_prijoy'; ...
    'se_L2_zee_strategy_opin';'se_L2_zee_strategy_sarc';'se_L2_zee_strategy_construct';...    
    'se_L2_zee_goal2_out_negative';'se_L2_zee_goal2_in_both_positive';'se_L2_zee_anger';'se_L2_zee_fear';...
    'se_L2_zee_disgust';'se_L2_zee_sadness';'se_L2_zee_enthop';'se_L2_zee_prijoy'; ...
    'se_tweet_nr3';'se__cons';'drop';'regnum'};
    
for type=1:3

    data = cell2table(cell(0,length(varnames2)),'VariableNames', varnames2);
    jjs=tree_data.regnum(tree_data.root_type==type);

for j=1:length(jjs)
    try
    j
    temp=readtable(pathreg + "regs_extsp_d_basic_50_" + num2str(j) +".xlsx.csv",'Format','%s %s','ReadRowNames',false);
    temp(end,:)=[];
    for i=2:2:height(temp)-2
        if length(temp{i,1}{1})>3
            
            % Remove = and quotes, convert to number
            coef = str2double(regexprep(temp{i,2}{1},'[="()]',''));
            se = str2double(regexprep(temp{i+1,2}{1},'[="()]',''));
            name = regexprep(temp{i,1}{1},'[="()]','');
            name = strrep(name, 'L.', 'L1_');
            name = strrep(name, 'L2.', 'L2_');
            se_name=['se_' name];
            
            data{j,strcmp(name,varnames2)}=coef;
            data{j,strcmp(se_name,varnames2)}=se;
        end
    end
    data{j,strcmp("N",varnames2)}=str2double(regexprep(temp{height(temp),2}{1},'[="()]',''));
    data{j,end}=j;    
    end
end
data.Properties.VariableNames{'_cons'} = 'cons';
data.Properties.VariableNames{'se__cons'} = 'se_cons';
temp=table2array(data); temp(temp==0)=nan;data{:,:}=temp; 
writetable(data,pathreg + "for_meta_type" + num2str(type) + ".xlsx");

end


%% import results of ardl and prep for meta in stata - hate joint 
pathreg="C:\Users\mirta\Dropbox\SFI Reconquista\00 strategies\analyses\trees50\hate_joint_rob3\";

varnames={'L.zee_speech_hate_yes';'L2.zee_speech_hate_yes';'zee_strategy_opin';'zee_strategy_sarc';'zee_strategy_construct';...    
    'zee_goal2_out_negative';'zee_goal2_in_both_positive';'zee_anger';'zee_fear';...
    'zee_disgust';'zee_sadness';'zee_enthop';'zee_prijoy'; ...
    'L.zee_strategy_opin';'L.zee_strategy_sarc';'L.zee_strategy_construct';...    
    'L.zee_goal2_out_negative';'L.zee_goal2_in_both_positive';'L.zee_anger';'L.zee_fear';...
    'L.zee_disgust';'L.zee_sadness';'L.zee_enthop';'L.zee_prijoy'; ...
    'L2.zee_strategy_opin';'L2.zee_strategy_sarc';'L2.zee_strategy_construct';...    
    'L2.zee_goal2_out_negative';'L2.zee_goal2_in_both_positive';'L2.zee_anger';'L2.zee_fear';...
    'L2.zee_disgust';'L2.zee_sadness';'L2.zee_enthop';'L2.zee_prijoy'; ...
    'tweet_nr3';'_cons';'N'};
varnames2= ...
    {'L1_zee_speech_hate_yes';'L2_zee_speech_hate_yes';'zee_strategy_opin';'zee_strategy_sarc';'zee_strategy_construct';...    
    'zee_goal2_out_negative';'zee_goal2_in_both_positive';'zee_anger';'zee_fear';...
    'zee_disgust';'zee_sadness';'zee_enthop';'zee_prijoy'; ...
    'L1_zee_strategy_opin';'L1_zee_strategy_sarc';'L1_zee_strategy_construct';...    
    'L1_zee_goal2_out_negative';'L1_zee_goal2_in_both_positive';'L1_zee_anger';'L1_zee_fear';...
    'L1_zee_disgust';'L1_zee_sadness';'L1_zee_enthop';'L1_zee_prijoy'; ...
    'L2_zee_strategy_opin';'L2_zee_strategy_sarc';'L2_zee_strategy_construct';...    
    'L2_zee_goal2_out_negative';'L2_zee_goal2_in_both_positive';'L2_zee_anger';'L2_zee_fear';...
    'L2_zee_disgust';'L2_zee_sadness';'L2_zee_enthop';'L2_zee_prijoy'; ...
    'tweet_nr3';'_cons';'N';...
    'se_L1_zee_speech_hate_yes';'se_L2_zee_speech_hate_yes';'se_zee_strategy_opin';'se_zee_strategy_sarc';'se_zee_strategy_construct';...    
    'se_zee_goal2_out_negative';'se_zee_goal2_in_both_positive';'se_zee_anger';'se_zee_fear';...
    'se_zee_disgust';'se_zee_sadness';'se_zee_enthop'; 'se_zee_prijoy';...
    'se_L1_zee_strategy_opin';'se_L1_zee_strategy_sarc';'se_L1_zee_strategy_construct';...    
    'se_L1_zee_goal2_out_negative';'se_L1_zee_goal2_in_both_positive';'se_L1_zee_anger';'se_L1_zee_fear';...
    'se_L1_zee_disgust';'se_L1_zee_sadness';'se_L1_zee_enthop';'se_L1_zee_prijoy'; ...
    'se_L2_zee_strategy_opin';'se_L2_zee_strategy_sarc';'se_L2_zee_strategy_construct';...    
    'se_L2_zee_goal2_out_negative';'se_L2_zee_goal2_in_both_positive';'se_L2_zee_anger';'se_L2_zee_fear';...
    'se_L2_zee_disgust';'se_L2_zee_sadness';'se_L2_zee_enthop';'se_L2_zee_prijoy'; ...
    'se_tweet_nr3';'se__cons';'drop';'regnum'};
    
for type=1:3

    data = cell2table(cell(0,length(varnames2)),'VariableNames', varnames2);
    jjs=tree_data.regnum(tree_data.root_type==type);


for j=1:length(jjs)
    try
    j
    temp=readtable(pathreg + "regs_hate_d_basic_50_" + num2str(j) +".xlsx.csv",'Format','%s %s','ReadRowNames',false);
    temp(end,:)=[];
    for i=2:2:height(temp)-2
        if length(temp{i,1}{1})>3
            
            % Remove = and quotes, convert to number
            coef = str2double(regexprep(temp{i,2}{1},'[="()]',''));
            se = str2double(regexprep(temp{i+1,2}{1},'[="()]',''));
            name = regexprep(temp{i,1}{1},'[="()]','');
            name = strrep(name, 'L.', 'L1_');
            name = strrep(name, 'L2.', 'L2_');
            se_name=['se_' name];
            
            data{j,strcmp(name,varnames2)}=coef;
            data{j,strcmp(se_name,varnames2)}=se;
        end
    end
    data{j,strcmp("N",varnames2)}=str2double(regexprep(temp{height(temp),2}{1},'[="()]',''));
    data{j,end}=j;    
    end
end
data.Properties.VariableNames{'_cons'} = 'cons';
data.Properties.VariableNames{'se__cons'} = 'se_cons';
temp=table2array(data); temp(temp==0)=nan;data{:,:}=temp; 
writetable(data,pathreg + "for_meta_type" + num2str(type) + ".xlsx");

end



%% import results of ardl and prep for meta in stata - extreme speakers joint 
pathreg="C:\Users\mirta\Dropbox\SFI Reconquista\00 strategies\analyses\trees50\extind_joint_rob3\";

varnames={'L.zee_user_group_70e';'L2.zee_user_group_70e';'zee_strategy_opin';'zee_strategy_sarc';'zee_strategy_construct';...    
    'zee_goal2_out_negative';'zee_goal2_in_both_positive';'zee_anger';'zee_fear';...
    'zee_disgust';'zee_sadness';'zee_enthop';'zee_prijoy'; ...
    'L.zee_strategy_opin';'L.zee_strategy_sarc';'L.zee_strategy_construct';...    
    'L.zee_goal2_out_negative';'L.zee_goal2_in_both_positive';'L.zee_anger';'L.zee_fear';...
    'L.zee_disgust';'L.zee_sadness';'L.zee_enthop';'L.zee_prijoy'; ...
    'L2.zee_strategy_opin';'L2.zee_strategy_sarc';'L2.zee_strategy_construct';...    
    'L2.zee_goal2_out_negative';'L2.zee_goal2_in_both_positive';'L2.zee_anger';'L2.zee_fear';...
    'L2.zee_disgust';'L2.zee_sadness';'L2.zee_enthop';'L2.zee_prijoy'; ...
    'tweet_nr3';'_cons';'N'};
varnames2= ...
    {'L1_zee_user_group_70e';'L2_zee_user_group_70e';'zee_strategy_opin';'zee_strategy_sarc';'zee_strategy_construct';...    
    'zee_goal2_out_negative';'zee_goal2_in_both_positive';'zee_anger';'zee_fear';...
    'zee_disgust';'zee_sadness';'zee_enthop';'zee_prijoy'; ...
    'L1_zee_strategy_opin';'L1_zee_strategy_sarc';'L1_zee_strategy_construct';...    
    'L1_zee_goal2_out_negative';'L1_zee_goal2_in_both_positive';'L1_zee_anger';'L1_zee_fear';...
    'L1_zee_disgust';'L1_zee_sadness';'L1_zee_enthop';'L1_zee_prijoy'; ...
    'L2_zee_strategy_opin';'L2_zee_strategy_sarc';'L2_zee_strategy_construct';...    
    'L2_zee_goal2_out_negative';'L2_zee_goal2_in_both_positive';'L2_zee_anger';'L2_zee_fear';...
    'L2_zee_disgust';'L2_zee_sadness';'L2_zee_enthop';'L2_zee_prijoy'; ...
    'tweet_nr3';'_cons';'N';...
    'se_L1_zee_user_group_70e';'se_L2_zee_user_group_70e';'se_zee_strategy_opin';'se_zee_strategy_sarc';'se_zee_strategy_construct';...    
    'se_zee_goal2_out_negative';'se_zee_goal2_in_both_positive';'se_zee_anger';'se_zee_fear';...
    'se_zee_disgust';'se_zee_sadness';'se_zee_enthop'; 'se_zee_prijoy';...
    'se_L1_zee_strategy_opin';'se_L1_zee_strategy_sarc';'se_L1_zee_strategy_construct';...    
    'se_L1_zee_goal2_out_negative';'se_L1_zee_goal2_in_both_positive';'se_L1_zee_anger';'se_L1_zee_fear';...
    'se_L1_zee_disgust';'se_L1_zee_sadness';'se_L1_zee_enthop';'se_L1_zee_prijoy'; ...
    'se_L2_zee_strategy_opin';'se_L2_zee_strategy_sarc';'se_L2_zee_strategy_construct';...    
    'se_L2_zee_goal2_out_negative';'se_L2_zee_goal2_in_both_positive';'se_L2_zee_anger';'se_L2_zee_fear';...
    'se_L2_zee_disgust';'se_L2_zee_sadness';'se_L2_zee_enthop';'se_L2_zee_prijoy'; ...
    'se_tweet_nr3';'se__cons';'drop';'regnum'};
    
for type=1:3

    data = cell2table(cell(0,length(varnames2)),'VariableNames', varnames2);
    jjs=tree_data.regnum(tree_data.root_type==type);


for j=1:length(jjs)
    try
    j
    temp=readtable(pathreg + "regs_extind_d_basic_50_" + num2str(j) +".xlsx.csv",'Format','%s %s','ReadRowNames',false);
    temp(end,:)=[];
    for i=2:2:height(temp)-2
        if length(temp{i,1}{1})>3
            
            % Remove = and quotes, convert to number
            coef = str2double(regexprep(temp{i,2}{1},'[="()]',''));
            se = str2double(regexprep(temp{i+1,2}{1},'[="()]',''));
            name = regexprep(temp{i,1}{1},'[="()]','');
            name = strrep(name, 'L.', 'L1_');
            name = strrep(name, 'L2.', 'L2_');
            se_name=['se_' name];
            
            data{j,strcmp(name,varnames2)}=coef;
            data{j,strcmp(se_name,varnames2)}=se;
        end
    end
    data{j,strcmp("N",varnames2)}=str2double(regexprep(temp{height(temp),2}{1},'[="()]',''));
    data{j,end}=j;    
    end
end
data.Properties.VariableNames{'_cons'} = 'cons';
data.Properties.VariableNames{'se__cons'} = 'se_cons';
temp=table2array(data); temp(temp==0)=nan;data{:,:}=temp; 
writetable(data,pathreg + "for_meta_type" + num2str(type) + ".xlsx");

end
