%% import results of ardls done in ardl_trees.do and prep for meta_analysis in stata (also in ardl_trees.do) - shown for toxicity, equivalent for other 4 outcomes
pathreg="D:\Dropbox\SFI Reconquista\00 strategies\analyses\trees50\tox_joint_rob2\";

varnames={'L.zee_tox';'zee_strategy_opin';'zee_strategy_sarc';'zee_strategy_construct';...    
    'zee_goal2_out_negative';'zee_goal2_in_both_positive';'zee_anger';'zee_fear';...
    'zee_disgust';'zee_sadness';'zee_enthop';'zee_prijoy'; ...
    'LD.zee_tox';'D.zee_strategy_opin';'D.zee_strategy_sarc';'D.zee_strategy_construct';...    
    'D.zee_goal2_out_negative';'D.zee_goal2_in_both_positive';'D.zee_anger';'D.zee_fear';...
    'D.zee_disgust';'D.zee_sadness';'D.zee_enthop';'D.zee_prijoy'; ...
    'LD.zee_strategy_opin';'LD.zee_strategy_sarc';'LD.zee_strategy_construct';...    
    'LD.zee_goal2_out_negative';'LD.zee_goal2_in_both_positive';'LD.zee_anger';'LD.zee_fear';...
    'LD.zee_disgust';'LD.zee_sadness';'LD.zee_enthop';'LD.zee_prijoy'; ...
    'tweet_nr3';'_cons';'N'};
varnames2= ...
    {'L_zee_tox';'zee_strategy_opin';'zee_strategy_sarc';'zee_strategy_construct';...    s
    'zee_goal2_out_negative';'zee_goal2_in_both_positive';'zee_anger';'zee_fear';...
    'zee_disgust';'zee_sadness';'zee_enthop';'zee_prijoy'; ...
    'LD_zee_tox';'D_zee_strategy_opin';'D_zee_strategy_sarc';'D_zee_strategy_construct';...    
    'D_zee_goal2_out_negative';'D_zee_goal2_in_both_positive';'D_zee_anger';'D_zee_fear';...
    'D_zee_disgust';'D_zee_sadness';'D_zee_enthop';'D_zee_prijoy'; ...
    'LD_zee_strategy_opin';'LD_zee_strategy_sarc';'LD_zee_strategy_construct';...    
    'LD_zee_goal2_out_negative';'LD_zee_goal2_in_both_positive';'LD_zee_anger';'LD_zee_fear';...
    'LD_zee_disgust';'LD_zee_sadness';'LD_zee_enthop';'LD_zee_prijoy'; ...
    'tweet_nr3';'cons';'N';...
    'se_L_zee_tox';'se_zee_strategy_opin';'se_zee_strategy_sarc';'se_zee_strategy_construct';...    
    'se_zee_goal2_out_negative';'se_zee_goal2_in_both_positive';'se_zee_anger';'se_zee_fear';...
    'se_zee_disgust';'se_zee_sadness';'se_zee_enthop'; 'se_zee_prijoy';...
    'se_LD_zee_tox';'se_D_zee_strategy_opin';'se_D_zee_strategy_sarc';'se_D_zee_strategy_construct';...    
    'se_D_zee_goal2_out_negative';'se_D_zee_goal2_in_both_positive';'se_D_zee_anger';'se_D_zee_fear';...
    'se_D_zee_disgust';'se_D_zee_sadness';'se_D_zee_enthop';'se_D_zee_prijoy'; ...
    'se_LD_zee_strategy_opin';'se_LD_zee_strategy_sarc';'se_LD_zee_strategy_construct';...    
    'se_LD_zee_goal2_out_negative';'se_LD_zee_goal2_in_both_positive';'se_LD_zee_anger';'se_LD_zee_fear';...
    'se_LD_zee_disgust';'se_LD_zee_sadness';'se_LD_zee_enthop';'se_LD_zee_prijoy'; ...
    'se_tweet_nr3';'se_cons';'drop';'regnum'};
    
data = cell2table(cell(0,length(varnames2)),'VariableNames', varnames2);

for j=1:3660
    try
    j
    temp=readtable(pathreg + "regs_tox_d_basic_50_" + num2str(j) +".xlsx.csv",'ReadRowNames',true);
    x=temp{strcmp(temp{:,3},"")==0,3}; temp{4:4+(vmax-1)*2-1,2}=x(2:end-1,:); 
    temp(:,3)=[]; temp(strcmp(temp{:,2},','),:)=[]; temp(end,:)=[];
    for i=1:height(temp)%-1
        if length(temp{i,1}{1})>1
            data{j,(strcmp(extractBefore(temp{i,1}{1},length(temp{i,1}{1})),varnames))}=str2num(temp{i,2}{1});
            try; data{j,length(varnames)+find(strcmp(extractBefore(temp{i,1}{1},length(temp{i,1}{1})),varnames))}=str2num(temp{i+1,2}{1}); end
        end
    end
    data{j,end-1}=str2num(temp{height(temp)-1,2}{1});
    data{j,end}=j;    
    end
end

temp=table2array(data); temp(temp==0)=nan;data{:,:}=temp; 
writetable(data,pathreg + "for_meta.xlsx");